# Generated by Django 5.1.6 on 2025-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_num', models.DecimalField(decimal_places=3, max_digits=7)),
                ('second_num', models.DecimalField(decimal_places=3, max_digits=7)),
                ('operators', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
